name: Main
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12.16.1-alpine
    name: Node
    steps:
      - name: Install dependencies
        run: apk update && apk add git

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk update && apk add curl bash

      - name: Install qlty
        shell: bash
        run: |
          curl https://qlty.sh/install.sh | bash
      
      - name: Run qlty
        shell: bash
        run: |
          export QLTY_INSTALL="$HOME/.qlty"
          export PATH="$QLTY_INSTALL/bin:$PATH"
          pwd
          env
          ls -al
          git config --global --add safe.directory "$PWD"
          git status
          qlty coverage publish --token token missing.lcov
